@base_url = "http://localhost:3333"

# @name get_hello
GET {{base_url}}/hello

### 
# @name auth
POST {{base_url}}/auth
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}